name: Forum Fusion

on:
  pull_request:
  branches:
    - main
  push:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2

      - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
      - name: Copy .env file
        run: |
        cp .env.ci .env

      - name: Install Composer
        run: |
        composer install --no-interaction

      - name: Run test
        run: |
        vendor/bin/phpunit          